name: ffb6d
channels:
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.8.2
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - opencv=3.4.4
  - cython
  - scipy
  - pip
  - pip:
    - numpy
    - matplotlib
    - h5py
    - pyyaml
    - future
    - transforms3d
    - scikit_image
    - lmdb
    - cffi
    - easydict
    - plyfile
    - glumpy