name: ffb6d
channels:
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.8.2
  - torchvision=0.9.2
  - torchaudio=0.8.2
  - cudatoolkit=10.2
  - opencv=3.4.4
  - h5py
  - cython
  - numpy
  - pyyaml
  - future
  - scipy=1.4.1
  - matplotlib
  - pip:
    - transforms3d==0.3.1
    - scikit_image==0.13.1
    - lmdb==0.94
    - cffi==1.11.5
    - easydict==1.7
    - plyfile==0.6
    - glumpy==1.0.6