name: ffb6d
channels:
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.8.2
  - torchvision=0.9.2
  - torchaudio=0.8.2
  - cudatoolkit=10.2
  - opencv=3.4.4
  - h5py
  - cython
  - numpy
  - pyyaml
  - future
  - scipy
  - matplotlib
  - pip
  - pip:
    - transforms3d
    - scikit_image
    - lmdb
    - cffi
    - easydict
    - plyfile
    - glumpy